# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-07 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='instagram.Profile')),
                ('imagecomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_comments', to='instagram.Image')),
            ],
        ),
    ]
